language: node_js
notifications:
  email: true
node_js: 16.15.0
cache:
  directories:
    - "node_modules"
jobs:
  include:
    - stage: test
      script:
        - npm run test
        - npm run build
    - stage: deploy
      deploy:
        provider: pages
        github_token: $GITHUB_TOKEN
        skip_cleanup: true
        on:
          branch: main
